from pathlib import Path

# Root directory for the learning roadmap.
root = Path("Basic Python")

# Structured phase-to-concepts mapping.
phases = {
    "01_Getting_Started": [
        "01_What_is_Python",
        "02_Installing_Python",
        "03_Running_Python",
        "04_Python_Interpreter_vs_Script",
        "05_IDEs",
        "06_Comments",
        "07_Input_and_Output",
        "08_Variables",
        "09_Naming_Conventions",
        "10_Keywords",
    ],
    "02_Data_Types": [
        "01_Numbers",
        "02_Integers",
        "03_Floats",
        "04_Complex_Numbers",
        "05_Strings",
        "06_String_Indexing",
        "07_String_Slicing",
        "08_String_Methods",
        "09_f_Strings",
        "10_Boolean",
        "11_None",
        "12_Type_Conversion",
        "13_type_Function",
        "14_isinstance_Function",
    ],
    "03_Operators": [
        "01_Arithmetic_Operators",
        "02_Assignment_Operators",
        "03_Comparison_Operators",
        "04_Logical_Operators",
        "05_Identity_Operators",
        "06_Membership_Operators",
        "07_Bitwise_Operators",
        "08_Operator_Precedence",
    ],
    "04_Control_Flow": [
        "01_if",
        "02_if_else",
        "03_if_elif_else",
        "04_Nested_if",
        "05_match_case",
    ],
    "05_Loops": [
        "01_while_Loop",
        "02_for_Loop",
        "03_range",
        "04_Nested_Loops",
        "05_break",
        "06_continue",
        "07_pass",
        "08_else_with_Loops",
    ],
    "06_Collections": [
        "01_Lists",
        "02_List_Indexing",
        "03_List_Slicing",
        "04_List_Methods",
        "05_List_Comprehension",
        "06_Tuples",
        "07_Tuple_Operations",
        "08_Packing_and_Unpacking",
        "09_Sets",
        "10_Set_Operations",
        "11_Set_Methods",
        "12_Dictionaries",
        "13_Accessing_Dictionary_Values",
        "14_Dictionary_Methods",
        "15_Dictionary_Comprehension",
    ],
    "07_Functions": [
        "01_Defining_Functions",
        "02_Parameters",
        "03_Return_Values",
        "04_Default_Arguments",
        "05_Keyword_Arguments",
        "06_Positional_Arguments",
        "07_args",
        "08_kwargs",
        "09_Lambda_Functions",
        "10_Variable_Scope",
        "11_Local_Scope",
        "12_Global_Scope",
        "13_nonlocal",
        "14_Recursion",
    ],
    "08_Modules": [
        "01_import",
        "02_from_import",
        "03_Module_Aliasing",
        "04_Standard_Library",
        "05_Creating_Modules",
        "06_Packages",
    ],
    "09_Exception_Handling": [
        "01_Errors_vs_Exceptions",
        "02_try",
        "03_except",
        "04_else",
        "05_finally",
        "06_raise",
        "07_Custom_Exceptions",
    ],
    "10_File_Handling": [
        "01_Opening_Files",
        "02_Reading_Files",
        "03_Writing_Files",
        "04_Appending_Files",
        "05_with_Statement",
        "06_File_Paths",
        "07_CSV_Basics",
        "08_JSON_Basics",
    ],
    "11_Object_Oriented_Programming": [
        "01_Classes",
        "02_Objects",
        "03_Constructors",
        "04_Instance_Variables",
        "05_Class_Variables",
        "06_Methods",
        "07_Inheritance",
        "08_Polymorphism",
        "09_Encapsulation",
        "10_Abstraction",
        "11_Magic_Methods",
        "12_Dataclasses",
    ],
    "12_Iterators_and_Generators": [
        "01_Iterables",
        "02_Iterators",
        "03_Generator_Functions",
        "04_yield",
        "05_Generator_Expressions",
    ],
    "13_Functional_Programming": [
        "01_map",
        "02_filter",
        "03_reduce",
        "04_zip",
        "05_enumerate",
        "06_any",
        "07_all",
        "08_sorted",
        "09_key_Function",
    ],
    "14_Pythonic_Features": [
        "01_List_Comprehensions",
        "02_Dictionary_Comprehensions",
        "03_Set_Comprehensions",
        "04_Ternary_Operator",
        "05_Multiple_Assignment",
        "06_Unpacking",
        "07_Walrus_Operator",
        "08_Context_Managers",
    ],
    "15_Built_in_Functions": [
        "01_len",
        "02_sum",
        "03_max",
        "04_min",
        "05_abs",
        "06_round",
        "07_sorted",
        "08_reversed",
        "09_range",
        "10_enumerate",
        "11_zip",
        "12_input",
        "13_print",
        "14_open",
        "15_dir",
        "16_help",
        "17_id",
        "18_hash",
        "19_chr",
        "20_ord",
        "21_eval",
        "22_isinstance",
        "23_type",
    ],
    "16_Standard_Library": [
        "01_math",
        "02_random",
        "03_statistics",
        "04_datetime",
        "05_time",
        "06_os",
        "07_pathlib",
        "08_shutil",
        "09_sys",
        "10_collections",
        "11_itertools",
        "12_functools",
        "13_pprint",
        "14_json",
        "15_csv",
        "16_re",
    ],
    "17_Projects": [
        "01_Calculator",
        "02_Guess_the_Number",
        "03_To_Do_List",
        "04_Contact_Book",
        "05_Student_Management_System",
        "06_Expense_Tracker",
        "07_Password_Generator",
        "08_File_Organizer",
        "09_Quiz_Application",
        "10_Library_Management_System",
        "11_Inventory_Management_System",
        "12_Banking_System",
        "13_Text_Analyzer",
        "14_Weather_App",
        "15_CSV_Data_Analyzer",
    ],
}

# Create the root directory if it does not already exist.
root.mkdir(exist_ok=True)

# Create each phase folder and its empty Python files.
for phase_name, concepts in phases.items():
    phase_dir = root / phase_name
    phase_dir.mkdir(exist_ok=True)

    for concept in concepts:
        file_path = phase_dir / f"{concept}.py"
        file_path.touch(exist_ok=True)