from pathlib import Path

ROADMAP = {
    "01_Advanced_Python": [
        "01_Decorators",
        "02_Nested_Functions",
        "03_Closures",
        "04_Higher_Order_Functions",
        "05_Context_Managers",
        "06_Descriptors",
        "07_Properties",
        "08_Static_Methods",
        "09_Class_Methods",
        "10_Metaclasses",
        "11_Magic_Methods",
        "12_Data_Classes",
        "13_NamedTuple",
        "14_DefaultDict",
        "15_Counter",
        "16_Deque",
        "17_ChainMap",
        "18_TypedDict",
        "19_Protocols",
        "20_Generics",
    ],
    "02_Data_Structures_and_Algorithms": [
        "01_Time_Complexity",
        "02_Space_Complexity",
        "03_Arrays",
        "04_Linked_List",
        "05_Stack",
        "06_Queue",
        "07_Hash_Table",
        "08_Heap",
        "09_Tree",
        "10_Binary_Search_Tree",
        "11_Graph",
        "12_Searching",
        "13_Sorting",
        "14_Recursion",
        "15_Dynamic_Programming",
        "16_Greedy_Algorithms",
        "17_Backtracking",
        "18_Graph_Algorithms",
    ],
    "03_Advanced_Object_Oriented_Programming": [
        "01_SOLID_Principles",
        "02_Composition",
        "03_Aggregation",
        "04_Association",
        "05_Dependency_Injection",
        "06_Abstract_Base_Classes",
        "07_Interfaces",
        "08_Design_Patterns",
        "09_Factory_Pattern",
        "10_Singleton",
        "11_Strategy",
        "12_Observer",
        "13_Builder",
    ],
    "04_Modern_Python_Features": [
        "01_Type_Hints",
        "02_typing_Module",
        "03_Annotations",
        "04_Pattern_Matching",
        "05_Walrus_Operator",
        "06_Slots",
        "07_Async_Syntax",
        "08_F_String_Advanced",
        "09_Pathlib",
        "10_Enums",
    ],
    "05_Testing_and_Debugging": [
        "01_unittest",
        "02_pytest",
        "03_Mocking",
        "04_Test_Coverage",
        "05_Debugging",
        "06_Breakpoints",
        "07_Logging",
        "08_Profiling",
        "09_Exception_Tracing",
    ],
    "06_Project_Architecture": [
        "01_Project_Structure",
        "02_Modular_Programming",
        "03_Code_Organization",
        "04_Configuration_Management",
        "05_Environment_Variables",
        "06_Reusable_Code",
        "07_Clean_Code",
        "08_Documentation",
        "09_PEP8",
        "10_Type_Checking",
    ],
    "07_Virtual_Environments_and_Packaging": [
        "01_venv",
        "02_virtualenv",
        "03_pip",
        "04_requirements",
        "05_pyproject_toml",
        "06_setuptools",
        "07_Packaging",
        "08_Publishing_Packages",
        "09_Poetry",
        "10_uv",
    ],
    "08_Database_Programming": [
        "01_SQLite",
        "02_PostgreSQL",
        "03_SQLAlchemy",
        "04_ORM",
        "05_CRUD",
        "06_Transactions",
        "07_Connection_Pooling",
        "08_Migrations",
    ],
    "09_Web_and_API_Programming": [
        "01_HTTP",
        "02_REST_API",
        "03_JSON",
        "04_Requests",
        "05_HTTPX",
        "06_FastAPI_Basics",
        "07_API_Authentication",
        "08_File_Upload",
        "09_API_Testing",
        "10_WebSockets",
    ],
    "10_Concurrency_and_Parallelism": [
        "01_Threading",
        "02_Multiprocessing",
        "03_Asyncio",
        "04_Coroutines",
        "05_Task_Scheduling",
        "06_Concurrent_Futures",
        "07_Queues",
        "08_Process_Pools",
    ],
    "11_File_Formats_and_Data_Processing": [
        "01_CSV",
        "02_JSON",
        "03_XML",
        "04_YAML",
        "05_Excel_OpenPyXL",
        "06_Parquet",
        "07_HDF5",
        "08_Pickle",
        "09_Compression",
        "10_Path_Management",
    ],
    "12_Scientific_Computing": [
        "01_NumPy_Basics",
        "02_Array_Creation",
        "03_Array_Indexing",
        "04_Broadcasting",
        "05_Vectorization",
        "06_Linear_Algebra",
        "07_Random_Module",
        "08_Statistics",
        "09_Fourier_Transform",
        "10_Memory_Optimization",
        "11_SciPy_Overview",
        "12_Optimization",
        "13_Integration",
        "14_Interpolation",
        "15_Signal_Processing",
        "16_Sparse_Matrices",
        "17_Special_Functions",
        "18_ODE_Solvers",
    ],
    "13_Data_Analysis": [
        "01_Pandas_Basics",
        "02_Series",
        "03_DataFrames",
        "04_Indexing",
        "05_Filtering",
        "06_GroupBy",
        "07_Merge",
        "08_Join",
        "09_Pivot",
        "10_TimeSeries",
        "11_Missing_Data",
        "12_Data_Cleaning",
        "13_Feature_Engineering",
        "14_Categorical_Data",
        "15_Performance",
    ],
    "14_Data_Visualization": [
        "01_Matplotlib",
        "02_Figures",
        "03_Axes",
        "04_Line_Plots",
        "05_Bar_Plots",
        "06_Histograms",
        "07_Scatter_Plots",
        "08_Subplots",
        "09_Animations",
        "10_Seaborn",
        "11_Plotly",
        "12_Bokeh",
    ],
    "15_Machine_Learning_Foundations": [
        "01_scikit_learn",
        "02_Preprocessing",
        "03_Datasets",
        "04_Regression",
        "05_Classification",
        "06_Clustering",
        "07_Model_Evaluation",
        "08_Cross_Validation",
        "09_Pipelines",
        "10_Model_Persistence",
    ],
    "16_Numerical_Optimization": [
        "01_Gradient_Descent",
        "02_Convex_Optimization",
        "03_SciPy_Optimize",
        "04_Linear_Programming",
        "05_Nonlinear_Optimization",
        "06_Curve_Fitting",
        "07_Least_Squares",
    ],
    "17_Bioinformatics_and_Computational_Biology": [
        "01_Biopython",
        "02_SeqIO",
        "03_Blast",
        "04_PDB",
        "05_Entrez",
        "06_Phylogenetics",
        "07_GenBank",
        "08_FASTA",
        "09_Molecular_Data",
        "10_Protein_Analysis",
        "11_Genome_Analysis",
        "12_Bioinformatics_APIs",
    ],
    "18_Performance_Optimization": [
        "01_Profiling",
        "02_cProfile",
        "03_line_profiler",
        "04_Numba",
        "05_Cython",
        "06_Memory_Profiler",
        "07_Multiprocessing_Optimization",
        "08_Vectorization",
        "09_Caching",
        "10_LRU_Cache",
    ],
    "19_Professional_Python": [
        "01_Git_Integration",
        "02_Pre_commit",
        "03_Black",
        "04_Ruff",
        "05_isort",
        "06_Mypy",
        "07_Sphinx",
        "08_MkDocs",
        "09_CI_CD",
        "10_GitHub_Actions",
    ],
    "20_Intermediate_Projects": [
        "01_Data_Analysis_Pipeline",
        "02_CSV_Analytics_System",
        "03_Web_API_Client",
        "04_FastAPI_Backend",
        "05_Scientific_Calculator",
        "06_Gene_Sequence_Analyzer",
        "07_Protein_Structure_Parser",
        "08_Bioinformatics_Toolkit",
        "09_Data_Visualization_Dashboard",
        "10_SQL_Management_System",
        "11_Log_Analyzer",
        "12_Web_Scraper",
        "13_Stock_Data_Analyzer",
        "14_Simulation_Project",
        "15_Mini_Machine_Learning_Project",
    ],
}


def build_roadmap(root_name: str, roadmap: dict[str, list[str]]) -> Path:
    """Create the complete directory tree for the learning roadmap."""
    root = Path(root_name)
    root.mkdir(parents=True, exist_ok=True)

    for phase_name, topics in roadmap.items():
        phase_dir = root / phase_name
        phase_dir.mkdir(parents=True, exist_ok=True)

        for topic in topics:
            (phase_dir / f"{topic}.py").touch(exist_ok=True)

    return root


if __name__ == "__main__":
    build_roadmap("Intermediate Python", ROADMAP)